import type { Compiler, RspackPluginInstance } from "@rspack/core";

export class HotUpdaterPlugin implements RspackPluginInstance {
	apply(compiler: Compiler) {
		new compiler.webpack.BannerPlugin({
			banner: "// Generated by Repack",
			raw: true,
		}).apply(compiler);

		new compiler.webpack.BannerPlugin({
			banner: "// Generated by Repack",
			raw: true,
			footer: true,
		}).apply(compiler);
	}
}
